/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('ant-design-vue/es')['AutoComplete']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    HospitalBottom: typeof import('./src/components/hospital-bottom/index.vue')['default']
    HospitalTop: typeof import('./src/components/hospital-top/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
